export const ImagesAssets = {
   OTP_Gif:require('../../assets/images/otpvideo/verify.mp4'),
   conf:require('../../assets/images/modal_Img/confirmation.gif'),
   HeaderMenuIcon:require('../../assets/images/HeaderImages/side.png'),
   Calender:require('../../assets/images/VisitorImages/calendar.png'),
   mobileImage:require('../../assets/images/VisitorImages/mobiles.png'),
   arrowLeft:require('../../assets/images/HeaderImages/arrow-left.png'),
   Modi:require('../../assets/images/HeaderImages/Modi.jpg'),
   sucessful:require('../../assets/images/modal_Img/sucessful.mp4'),
   splash_background:require('../../assets/images/splashScreen/bg.png'),
   logo:require('../../assets/images/RoobarooLogo/logo.png'),
   login_background:require('../../assets/images/Login/bg2.png'),
   HeaderMenuIcon:require('../../assets/images/HeaderImages/side.png'),
   profile_organistation:require('../../assets/images/profile/org.png'),
   profile_mobile:require('../../assets/images/profile/mobile.png'),
   profile_email:require('../../assets/images/profile/email.png'),
   profile_address:require('../../assets/images/profile/address.png'),
   roobaroo_logo:require('../../assets/images/RoobarooLogo/logo.png'),
   home_colored:require('../../assets/images/drawer_img/home.png'),
   hemu:require('../../assets/images/drawer_img/hemu.jpeg'),
   calander_blue:require('../../assets/images/drawer_img/calendar.png'),
   visit_black:require('../../assets/images/drawer_img/visit.png'),
   visit_profile:require('../../assets/images/dashboard_img/visits.png'),

};